name: mkdoc_check
on:
  pull_request:
    branches:
      - 'devel'
    paths:
      - 'mkdocs.yml'
      - 'ansible_collections/arista/cvp/docs/**'
      - 'ansible_collections/arista/cvp/roles/**/README.md'
      - '.github/workflows/documentation-check.yml'
      - '.github/workflows/documentation-build.yml'
jobs:
  offline_validation:
    name: 'Validate mkdoc content'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'start docker-compose stack'
        run: |
          cp development/docker-compose.yml .
          sed -i 's/ansible-cvp\///g' docker-compose.yml
          docker-compose -f docker-compose.yml up -d webdoc_cvp
          docker-compose -f docker-compose.yml ps

      - name: 'test connectivity to mkdoc server'
        run: |
          sleep 30
          docker run --network container:webdoc_cvp appropriate/curl -s -I --retry 10 --retry-connrefused http://localhost:8000/
          docker ps

      - name: check links for 404
        run: |
          docker run --network container:webdoc_cvp raviqqe/muffet:1.5.7 http://127.0.0.1:8000 -e ".*fonts.gstatic.com.*" -e ".*edit.*" -f --limit-redirections=3 --timeout=30

      - name: 'stop docker-compose stack'
        run: |
          docker-compose -f docker-compose.yml down
